version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ca-central-1"
    AWS_ACCOUNT_ID: "448923944643"
    IMAGE_REPO_NAME: "node_base"
    IMAGE_TAG: "latest"

phases:
  install:
    commands:
      - "echo 'Install phase - verifying Docker and AWS CLI'"
      - "docker --version"
      - "aws --version"

  pre_build:
    commands:
      - "set -x"
      - "aws sts get-caller-identity"
      - "echo Region=$AWS_DEFAULT_REGION Account=$AWS_ACCOUNT_ID"
      - "aws ecr describe-repositories --repository-names \"$IMAGE_REPO_NAME\" --region \"$AWS_DEFAULT_REGION\" || aws ecr create-repository --repository-name \"$IMAGE_REPO_NAME\" --region \"$AWS_DEFAULT_REGION\""
      - |
        for i in 1 2 3; do
          aws ecr get-login-password --region "$AWS_DEFAULT_REGION" \
            | docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com" && break
          echo "ECR login attempt $i failed; retrying in $((i*i))s..."
          sleep $((i*i))
        done
      - "REPO_URI=\"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME\""
      - "echo Repo URI: $REPO_URI"

  build:
    commands:
      - "echo 'Build started on '$(date)"
      - "COMMIT_HASH=$(echo \"$CODEBUILD_RESOLVED_SOURCE_VERSION\" | cut -c 1-7)"
      - "IMAGE_TAG=${COMMIT_HASH:-$IMAGE_TAG}"
      - "docker build -t \"$IMAGE_REPO_NAME:$IMAGE_TAG\" ."
      - "docker tag \"$IMAGE_REPO_NAME:$IMAGE_TAG\" \"$REPO_URI:$IMAGE_TAG\""

  post_build:
    commands:
      - "docker push \"$REPO_URI:$IMAGE_TAG\""
      - "printf '[{\"name\":\"CHAOS_TEST\",\"imageUri\":\"%s\"}]' \"$REPO_URI:$IMAGE_TAG\" > imagedefinitions.json"
      - "echo 'Build completed on '$(date)"

artifacts:
  files:
    - "imagedefinitions.json"
